# Generated by Django 5.0.1 on 2024-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='familyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='plantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant/')),
            ],
        ),
        migrations.CreateModel(
            name='qrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr/')),
            ],
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientificName', models.CharField(max_length=100)),
                ('uses', models.TextField(blank=True, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('care', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('references', models.URLField(blank=True, null=True)),
                ('commonNameList', models.ManyToManyField(blank=True, related_name='comName', to='application.commonname')),
                ('familyNameList', models.ManyToManyField(blank=True, related_name='famName', to='application.familyname')),
                ('plantImageList', models.ManyToManyField(blank=True, related_name='plantImg', to='application.plantimage')),
                ('qrImageList', models.ManyToManyField(blank=True, related_name='qrImg', to='application.qrimage')),
            ],
        ),
    ]
