# Generated by Django 5.0.1 on 2024-02-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='qrImageList',
        ),
        migrations.DeleteModel(
            name='qrImage',
        ),
    ]
